name: 9eight9 Video Processor

on:
  workflow_dispatch:
    inputs:
      video_command:
        description: 'Command from n8n'
        required: true

jobs:
  execute-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Deno (To Solve YouTube Challenges)
        run: |
          curl -fsSL https://deno.land/x/install/install.sh | sh
          echo "/home/runner/.deno/bin" >> $GITHUB_PATH

      - name: Install Tools (ffmpeg & Latest yt-dlp)
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          # نصب مستقیم از سورس اصلی برای داشتن آخرین آپدیت‌های ضد‌بات
          python -m pip install -U https://github.com/yt-dlp/yt-dlp/archive/master.tar.gz

      - name: Running the Command
        run: |
          ${{ github.event.inputs.video_command }}

      - name: Send Result to Telegram
        if: success()
        run: |
          curl -v -F "video=@final_video.mp4" https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendVideo?chat_id=${{ secrets.TELEGRAM_CHAT_ID }}
